[features]
seeds = false
[programs.localnet]
token_withdraw = "3ERnPj1gQnKzagvWCjqZGskJszcLhunXuLfYqjuSvxBW"

[registry]
url = "https://api.apr.dev"
# url = "http://localhost:8899"

[provider]
cluster = "devnet"
wallet = "/home/rosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
